### ISSUE TITLE
Empresas não aparecem nos resultados quando os nomes possuem acentuação

### ISSUE THREAD

**Issue by dinhani** [msperlin/GetITRData#1]
Veja nos seguintes exemplos que a busca por empresas retornou resultados diferentes quando foi utilizado o acento na busca. Acredito que o ideal seria ignorar os acentos.

    gitrd.search.company('itau')

    Found 2 companies:
    ITAUSEG PARTICIPAÇÕES SA     | situation = CANCELADA | first date = 2011-03-31 | last date - 2012-09-30
    ITAUTEC S.A. - GRUPO ITAUTEC | situation = ATIVO | first date = 1998-09-30 | last date - 2017-06-30
 

    gitrd.search.company('itaú')

    Found 2 companies:
    ITAÚ UNIBANCO | situation = ATIVO | first date = 1998-09-30 | last date - 2017-06-30
    ITAÚSA        | situation = ATIVO | first date = 1998-09-30 | last date - 2017-06-30

**Comment by msperlin** [comment]
Oi dinhani. 

De acordo. Já modifiquei para ignorar acentos. Nova versão no github.

> gitrd.search.company('itaú')

Reading info file from github
Found 24023 lines for 605 companies  [Actives =  458  Inactives =  147 ]
Last file update:  2017-10-05

Found 4 companies:
ITAÚ UNIBANCO                | situation = ATIVO | first date = 1998-09-30 | last date - 2017-06-30
ITAÚSA                       | situation = ATIVO | first date = 1998-09-30 | last date - 2017-06-30
ITAUSEG PARTICIPAÇÕES SA     | situation = CANCELADA | first date = 2011-03-31 | last date - 2012-09-30
ITAUTEC S.A. - GRUPO ITAUTEC | situation = ATIVO | first date = 1998-09-30 | last date - 2017-06-30
